# Generated by Django 2.2.10 on 2020-02-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='allowed_membership',
            new_name='allowed_memberships',
        ),
    ]
